### ISSUE TITLE
Retorno do clique em investimentos

### ISSUE THREAD

**Issue by romulocollopy** [ecofunds/ecofunds#25]
Fase 1:
Colocar o link no título dos investimentos que aparecem no Infobox (ex: http://stage.ecofundsdatabase.org/investimentos/ficha-investimento/?id=816)

Fase 2:
Retornar lista de investimentos no lugar dos filtros, com descrições mínimas e link.
![image](https://f.cloud.github.com/assets/1958236/881948/38463692-f958-11e2-8211-b82a78d8441a.png)

**Comment by henriquebastos** [comment]
A fase 1 foi corrigida no #27. É legal abrir uma nova issue pra fase 2. Não ficou claro pra mim o que vc quer que aconteça no painel de filtros.

**Comment by romulocollopy** [comment]
A ideia é que a lista de resultados que é retornada no infobox retorne na lista de filtros, com layout próximo ao Google Maps (como se cada restaurante fosse um investimento) Considero uma feature pro fim do projeto, se houver tempo.

![image](https://f.cloud.github.com/assets/1958236/913488/576d9036-fe19-11e2-8c59-aa9a54d26b7c.png)
