### ISSUE TITLE
Alinhamento dos Filtros

### ISSUE THREAD

**Issue by romulocollopy** [ecofunds/ecofunds#26]
Integrar os filtros abaixo ao backbone, eliminando os demais:
- (projetos) nome do projeto, tipo de atividade, região (país, estado e município) e organização.
- (organização) nome da organização, tipo da organização, região apoiada (país, estado e município).
- (investimento) tipo de investimento, nome da organização, nome do projeto, região apoiada (país, estado e município).

**Comment by henriquebastos** [comment]
Abri um PR https://github.com/ecofunds/ecofunds/pull/27

Estou tendo problemas para adicionar a o filtro de cidades. A única tabela com um campo `city` é a de organização. Como esse filtro deveria funcionar em `projetos` e `investimento`?

Tentei fazer um malabarismo usando esse dado com o projeto, mas no mapa ficou esquisito mostrando projetos com location no nordeste, mas administrados por organizações no Rio de Janeiro.

**Comment by romulocollopy** [comment]
Pensando aqui... para fazer sentido o filtro de cidades noa projetos e
investimentos, só faz sentido se existir esse dado no modelo de projeto ou
investimento.

Então, ou a gente adiciona o campo, mesmo que esteja blank, ou desencana
dessa feature do filtro.

Como acordamos com a Camila de ter essa feature, acho que é o caso de
alterar o modelo e buscar lá. Não vamos nos preocupar muito com os dados
legados que estejam blank. Depois a gente preenche.

Rômulo Collopy
_+55 21 86357035
romulo.collopy@gmail.com_

Em 3 de agosto de 2013 16:29, Henrique Bastos
notifications@github.comescreveu:

**Comment by henriquebastos** [comment]
Eu acho melhor não _assumirmos_ nada pela Camila. Acho que ela precisa confirmar se isso é prioridade. Digo isso, pois se a funcionalidade vai estar disponível, mas sem uso, então ela não tem valor. Além disso, não falta coisas para fazermos no projeto com o pouco recurso que temos.
