### ISSUE TITLE
Retorno de polígono inesperado (Fauna)

### ISSUE THREAD

**Issue by romulocollopy** [ecofunds/ecofunds#4]
Entrei no http://stage.ecofundsdatabase.org/en/map/ e digitei "fauna" no campo "name" do filtro do mapa e o sistema retornou o suggestion quando o Rômulo clivou no 1º então o o mapa ativa um polígono no Peru, quando o projeto é de Salvador-BA.

Ao entrar na página http://stage.ecofundsdatabase.org/projetos/ficha-projeto/?id=63, referente ao projeto pesquisado no mapa, e clicando em "Project Location Map", ele vai para a URL com a busca do projeto (http://stage.ecofundsdatabase.org/pt-br/mapa/?s_project_name=Agrega%C3%A7%C3%B5es%20reprodutivas%20de%20peixes%20recifais%20no%20Brasil:%20Subs%C3%ADdio%20para%20o%20licenciamento%20ambiental%20de%20atividades%20de%20E&P%20(Explora%C3%A7%C3%A3o%20e%20Produ%C3%A7%C3%A3o)%20%E2%80%93%20Projeto%20Pr%C3%B3-Arribada%20-%20Carteira%20Fauna) e não retorna nenhum shape.

![busca-fauna-mapa](https://f.cloud.github.com/assets/1958236/737090/2ac12c48-e328-11e2-8753-5dcd94ed30f6.png)

**Comment by felipecruz** [comment]
Vamos pegar isso no próximo ciclo. Como o código mudou muito, vou fechar aqui.
