### ISSUE TITLE
Remover links em Detalhe de Projeto

### ISSUE THREAD

**Issue by felipecruz** [ecofunds/ecofunds#48]
No detalhe do projeto, remover "Estimated Annual Budget"
No detalhe do projeto remover o "Attachment"
No detalhe do projeto remover o "navigate map"
No detalhe do projeto remover o "print"

**Comment by felipecruz** [comment]
closed by: b2ffa51

**Comment by romulocollopy** [comment]
Beleza, mas no stage ainda não entrou, certo?
