### ISSUE TITLE
Simplificação do mapa para estabelecer um benchmark

### ISSUE THREAD

**Issue by henriquebastos** [ecofunds/ecofunds#5]
- Computar as centroids e "cachear".
- Eliminar shapefiles
- Medir o tempo de carga e registrar nesta issue.

**Comment by romulocollopy** [comment]
Mudar a ação de centralizar o mapa no marcador de onMouseOver para onClick

**Comment by felipecruz** [comment]
Tempo de resposta em stage.ecofundsdatabase.org = 299ms
