### ISSUE TITLE
Remover campos em detalhe de projeto

### ISSUE THREAD

**Issue by romulocollopy** [ecofunds/ecofunds#50]
No detalhe do projeto, remover:
    "Estimated Annual Budget"
    "Attachment"
    "Print"
    "investments" que mostraria os investimentos relacionados ao projeto.
    Do sidebar, o "navigate map"

**Comment by felipecruz** [comment]
Fala!! se nao me engano, fechei esse issue atual nesse aqui: #48 

Vou fechar, blz?
