### ISSUE TITLE
Crud Bad Gateway

### ISSUE THREAD

**Issue by romulocollopy** [ecofunds/ecofunds#58]
Estava adicionando várias atividades, quando começou a apresentar Bad Gateway ao adicionar qualquer coisa no crud.

http://stage.ecofundsdatabase.org/admin/crud/activity/add/

502 Bad Gateway

nginx/1.4.1

**Comment by henriquebastos** [comment]
Vou ver os logs. Algo deve ter matado o processo do Django.

## []'s,

Henrique Bastos
+55 21 9618-6180
http://henriquebastos.net
Twitter: henriquebastos
Gtalk: henrique@bastos.net
Skype: henriquebastos.net

**Comment by henriquebastos** [comment]
Parece que tudo está funcionando bem. Não consegui reproduzir o seu
problema.

**Comment by romulocollopy** [comment]
Era algo na sessão.

Continuou apresentando erro, mesmo após logout e login.
Tentei numa aba anônima e funcionou
Depois limpei a sessão e o cache e ficou tudo normal.
