### ISSUE TITLE
Agilizar deploy sem compilar numpy, scipy e matplotlib

### ISSUE THREAD

**Issue by henriquebastos** [ecofunds/ecofunds#7]
Duas opções são possíveis:
1. Paleta de cores em python;
2. Usar o numpy, scipy e matplotlib do sistema (apt-get) em vez do venv, e usar --site-packages para criar o venv.

**Comment by felipecruz** [comment]
Fechado Pelo https://github.com/ecofunds/ecofunds/pull/11
