### ISSUE TITLE
Usar production como ambiente de entrega estável

### ISSUE THREAD

**Issue by henriquebastos** [ecofunds/ecofunds#8]

**Comment by romulocollopy** [comment]
Me passa o settings.ini pro decouple?

**Comment by henriquebastos** [comment]
Tá no dropbox

## 

Henrique Bastos http://henriquebastos.net

Curso Welcome to the Django http://welcometothedjango.com.br
Aprenda Python e Django na Prática!

Twitter: @henriquebastos http://twitter.com/henriquebastos
Skype: henriquebastos.net
+55 21 9618-6180

**Comment by romulocollopy** [comment]
Valeu!

**Comment by felipecruz** [comment]
O settings.ini do Dropbox não está funcionando aqui.

**Comment by romulocollopy** [comment]
Ele aparentemente tá faltando o Header.
Se você põe na primeira linha um...

[Credentials]

... Ele roda. Mas ai dá problema no dj_database_url.

Rômulo Collopy
+55 21 86357035
Em 10/07/2013 20:08, "Felipe Cruz" notifications@github.com escreveu:

**Comment by henriquebastos** [comment]
Bota na 1a linha:

[settings]

**Comment by romulocollopy** [comment]
Eu fiz isso e ele reclamou de InterpolationSyntaxError por causa do  % na SECRET_KEY
![setingsini-error](https://f.cloud.github.com/assets/1958236/783605/4c8e1dc6-ea54-11e2-8310-bce61f5da25a.png)

Então eu tirei o % do settings.ini e ele reclamou do South
![south-error](https://f.cloud.github.com/assets/1958236/783607/55be5c26-ea54-11e2-91b7-10034bdf6728.png)

daí eu comentei o South no settings.py e ele reclamou que o settings.DATABASES precisa do valor da ENGINE.
![settings database-error](https://f.cloud.github.com/assets/1958236/783637/e43bd7ee-ea54-11e2-852b-747b60ed3545.png)

Então eu adicionei na ultima linha do settings.ini: 
DABATABASE_URL=mysql://root@localhost/ecofunds

Ai funcionou. Voltei o South e continuou funcionando. Só a SECRET_KEY que não rolou com o caracter %

**Comment by henriquebastos** [comment]
No ini, % precisa ser %%.

Eu vou atualizar o dropbox e aviso.

## 

Henrique Bastos

http://welcometothedjango.com.br
Aprenda Python e Django na Prática!

Twitter: @henriquebastos
Skype: henriquebastos.net
+55 21 9618-6180

**Comment by felipecruz** [comment]
galera.. o settings não funciona aqui de jeito algum.. estou usando a config de database normal, digamos assim.

**Comment by henriquebastos** [comment]
Atualizei a atualização do Rômulo no Dropbox

## 

Henrique Bastos http://henriquebastos.net

Curso Welcome to the Django http://welcometothedjango.com.br
Aprenda Python e Django na Prática!

Twitter: @henriquebastos http://twitter.com/henriquebastos
Skype: henriquebastos.net
+55 21 9618-6180
